name: Build & Publish

on:
  push:
    tags:
      - '[0-9].*'

jobs:
  build_wheels:
    name: Build Py3 Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # unshallow fetch for setuptools-scm

    - name: Use MSBuild (Windows only)
      uses: microsoft/setup-msbuild@v1.0.2
      if: matrix.os == 'windows-latest'

    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools

    - name: Build wheel
      run: python setup.py bdist_wheel

    - name: Build sdist (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: python setup.py sdist

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheelstorage
        path: ./dist/*
        if-no-files-found: error
        retention-days: 30
